version: '3.7'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: kuma
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /usr/src/django-blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django-blog
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
